name: Öykü Yarışmaları
description: >
    Hikaye, öykü, mikro öykü, roman yarışmalarının listelendiği adres
about: >
    Elimden geldiğince ülkemizde düzenlenen öykü yarışmalarını toplamayı amaçlıyorum. Siz de katkıda bulabilirsiniz.

master_repo: false
url: "uguratmaca.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo: logo.png

rtl: false
owner:
  name: whitepaper
  email: "info@uguratmaca.com"
  twitter: uguratm
  github: https://github.com/uguratmaca
  linkedin: https://www.linkedin.com/in/atmacaugur/

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
